config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  mount StripeEvent::Engine, at: '/stripe-webhooks'

  root to: 'pages#home'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :after_signup

  resources :houses do
    collection do
      get :onboarding
    end

    member do
      get :onboarding_link
      get :settings
    end

    resources( :bills, {only: [:edit, :update, :new, :create]})
    # Method (symbol, hash { key/symbol value/array})
    resources :memberships, only: [:index, :destroy]
    resources :shares, only: [:index] do
      collection do
        get :history
      end
    end

    resources :payments, only: [:show, :create]

    get 'pre_payment/:id', to: 'payments#pre_payment', as: 'pre_payment'
  end

  resources( :bills, {only: [:destroy]})

  resources :shares, only: [:edit, :update]



end

app/controllers/houses_controller.rb
class HousesController < ApplicationController
  before_action :set_house, only: [:show, :edit, :update, :destroy]
  layout "signup", only: [:onboarding]
  layout "navbar", only: [:settings]

  # /houses
  def index
    @houses = House.all
  end

  # /houses/:id
  def show
  end

# /houses/:new
  def new
    @house = House.new
  end

  def create
    @house = House.new(house_params)
    if @house.save
      @membership = Membership.create(user: current_user, house: @house)
      redirect_to onboarding_link_house_path(@house)
    else
      render :new
    end
  end

 # houses/1/edit
  def edit
  end

  def update
    if @house.update(house_params)
      redirect_to house_shares_path(@house)
    else
      render :new
    end
  end

  def destroy
    @house.destroy
    redirect_to houses_path
  end

  def onboarding
    # if current_user.houses.length > 0
    #   redirect_to house_shares_path(params[:house_id])
      @house = House.new
  end

  def onboarding_link
    @house = House.find(params[:id])
  end

  def settings
    @house = House.find(params[:id])
    @membership = Membership.where(user: current_user, house: @house).first
  end

  private

  def set_house
    @house = House.find(params[:id])
  end

  def house_params
    params.require(:house).permit(:name)
  end
end

app/views/houses/edit.html.erb
<%= image_tag "capital-logo.svg", alt: "logo", class: 'logo-top' %>

<%= simple_form_for(@house) do |f| %>
<div class="card-container house-input">
  <h6>Edit House:</h6>

    <%= f.input :name %>
    <%= f.input :email %>
    <h6>House Members:</h6>
    <div class="d-flex justify-content-between">
      <% @house.users.each do |user| %>
        <div class="round-members">
          <p style="color: #FFF3EC"><%= user.first_name%></p>
        </div>
      <% end %>
    </div>

</div>
  <div class="card-bottom">
    <%= link_to "Go back", settings_house_path(@house), class: "btn btn-info btn-sm"  %>
    <div class="form-actions next-button-container">
    <%= f.submit "Save", class: "btn btn-primary btn-sm" %>
    </div>
  </div>
<% end %>

app/views/houses/index.html.erb
<%= image_tag "capital-logo.svg", alt: "logo", class: 'logo-top' %>


<div class="card-container house-input">
  <div class="svg-house">
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 33.2 16.6" style='margin-bottom: 3rem;'><title>green-houserectangle</title><rect x="8.3" y="-8.3" width="16.6" height="33.2" transform="translate(24.9 -8.3) rotate(90)" fill="#81b3a3"/></svg>
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 46.95 23.47" style='transform: rotate(180deg);'><title>triangle-sand</title><polyline points="0 23.48 23.48 0 46.95 23.48" fill="#559CAD"/></svg>
  </div>
  <div class="form-margins">
      <h5>Choose a house to enter:</h5>
    <div class="house_choice">
      <% if @houses = current_user.houses  %>
        <% @houses.each do |house| %>
          <div class="text-center">
            <%= link_to house_shares_path(house) do %>
              <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="55" height="55">
                <path fill="none" d="M0 0h24v24H0z"/>
                <path d="M21 20a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V9.49a1 1 0 0 1 .386-.79l8-6.222a1 1 0 0 1 1.228 0l8 6.222a1 1 0 0 1 .386.79V20z" fill="$light-sand"/>
              </svg>
            <% end %>
              <p><%= link_to house.name, house_shares_path(house) %></p>
          </div>
            <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/houses/new.html.erb
<%= image_tag "capital-logo.svg", alt: "logo", class: 'logo-top' %>


<%= simple_form_for(@house) do |f| %>
<div class="card-container house-input">
  <div class="svg-house">
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 33.2 16.6" style='margin-bottom: 3rem;'><title>green-houserectangle</title><rect x="8.3" y="-8.3" width="16.6" height="33.2" transform="translate(24.9 -8.3) rotate(90)" fill="#81b3a3"/></svg>
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 46.95 23.47" style='transform: rotate(180deg);'><title>triangle-sand</title><polyline points="0 23.48 23.48 0 46.95 23.48" fill="#559CAD"/></svg>
  </div>
  <div class="form-margins">
    <h5 class="question">Have you named your house yet?</h5>
    <%= f.input :name, required: true, label: false, placeholder: 'name it now!' %>
  </div>
</div>
  <div class="align-button-right">
    <%= f.submit 'next', class: 'btn btn-primary btn-sm' %>
  </div>
<% end %>

app/views/houses/onboarding.html.erb
<%= image_tag "capital-logo.svg", alt: "logo", class: 'logo-top' %>


<%= simple_form_for(@house) do |f| %>
<div class="card-container house-input">
  <div class="svg-house">
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 33.2 16.6" style='margin-bottom: 3rem;'><title>green-houserectangle</title><rect x="8.3" y="-8.3" width="16.6" height="33.2" transform="translate(24.9 -8.3) rotate(90)" fill="#81b3a3"/></svg>
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 46.95 23.47" style='transform: rotate(180deg);'><title>triangle-sand</title><polyline points="0 23.48 23.48 0 46.95 23.48" fill="#559CAD"/></svg>
  </div>
  <div class="form-margins">
    <h5 class="question">Have you named your house yet?</h5>
    <%= f.input :name, required: true, label: false, placeholder: 'name it now!' %>
  </div>
</div>
  <div class="align-button-right">
    <%= f.submit 'next', class: 'btn btn-primary btn-sm' %>
  </div>
<% end %>
<!--


Host = creates house

Invitee = gets added to house... they only sign up with the house link
 -->

app/views/houses/onboarding_link.html.erb
<%= image_tag "capital-logo.svg", alt: "logo", class: 'logo-top' %>


<div class="card-container house-input">
  <div class="svg-house">
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 33.2 16.6" style='margin-bottom: 3rem;'><title>green-houserectangle</title><rect x="8.3" y="-8.3" width="16.6" height="33.2" transform="translate(24.9 -8.3) rotate(90)" fill="#81b3a3"/></svg>
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 46.95 23.47" style='transform: rotate(180deg);'><title>triangle-sand</title><polyline points="0 23.48 23.48 0 46.95 23.48" fill="#559CAD"/></svg>
  </div>
    <div class="form-margins">
      <h5 class="question mt-3">Invite your housemates to join with this link.</h5>
      <div class="link-area">
        <input type="text" value="<%= new_user_registration_url %>?house_id=<%= @house.id %>" id="myInput">
        <button id="copybtn">copy</button>
      </div>
    </div>
</div>
<div class="align-button-right">
  <%= link_to 'done', house_shares_path(@house), class: 'btn btn-primary btn-sm' %>
</div>

app/views/houses/settings.html.erb
<div class="mx-5 mt-5">
  <div class="round-name">
    <h1><%= current_user.initials %></h1>
  </div>
</div>

<div class="d-flex justify-content-center mt-3 mb-4">
  <div>
    <h3 class="text-center mr-1"> Hey, <%= current_user.first_name %>
    </h3>
  </div>
  <div>
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="14" height="14"><path fill="none" d="M0 0h24v24H0z"/><path d="M7.291 20.824L2 22l1.176-5.291A9.956 9.956 0 0 1 2 12C2 6.477 6.477 2 12 2s10 4.477 10 10-4.477 10-10 10a9.956 9.956 0 0 1-4.709-1.176zM7 12a5 5 0 0 0 10 0h-2a3 3 0 0 1-6 0H7z"/>
    </svg>
  </div>
</div>


<div class="ml-5">
  <h6>You</h6>
</div>

<div class="d-flex justify-content-between mx-5">
  <div class="round-small-you">
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24"><path fill="none" d="M0 0h24v24H0z"/><path d="M9.243 19H21v2H3v-4.243l9.9-9.9 4.242 4.244L9.242 19zm5.07-13.556l2.122-2.122a1 1 0 0 1 1.414 0l2.829 2.829a1 1 0 0 1 0 1.414l-2.122 2.121-4.242-4.242z"/>
    </svg>
  </div>
  <div class="round-small-text">
    <%= link_to "Update Details", edit_user_registration_path, class: " pull-left" %>
  </div>
  <div>
    <p>></p>
  </div>
</div>

<div class="ml-5">
  <h6>Houses</h6>
</div>

<div class="d-flex justify-content-between mx-5">
  <div class="round-small-house">
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="23" height="23"><path fill="none" d="M0 0h24v24H0z"/><path d="M20 20a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1v-9H1l10.327-9.388a1 1 0 0 1 1.346 0L23 11h-3v9zM7.5 13a4.5 4.5 0 1 0 9 0h-2a2.5 2.5 0 1 1-5 0h-2z"/></svg>
  </div>
  <div class="round-small-text">
     <%= link_to "House Details", edit_house_path(@house) %>
  </div>
  <div>
    <p>></p>
  </div>
</div>

<div class="d-flex justify-content-between mx-5">
  <div class="round-small-house">
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="23" height="23"><path fill="none" d="M0 0h24v24H0z"/><path d="M14 14.252V22H4a8 8 0 0 1 10-7.748zM12 13c-3.315 0-6-2.685-6-6s2.685-6 6-6 6 2.685 6 6-2.685 6-6 6zm6 4v-3h2v3h3v2h-3v3h-2v-3h-3v-2h3z"/></svg>
   </div>
   <div class="round-small-text">
    <%= link_to "Invite New Members", onboarding_link_house_path(@house) %>
    </div>
  <div>
    <p>></p>
  </div>
</div>

<div class="d-flex justify-content-between mx-5">
  <div class="round-small-house">
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="23" height="23"><path fill="none" d="M0 0h24v24H0z"/><path d="M10.313 11.566l7.94-7.94 2.121 2.121-1.414 1.414 2.121 2.121-3.535 3.536-2.121-2.121-2.99 2.99a5.002 5.002 0 0 1-7.97 5.849 5 5 0 0 1 5.848-7.97zm-.899 5.848a2 2 0 1 0-2.828-2.828 2 2 0 0 0 2.828 2.828z"/></svg>
  </div>
  <div class="round-small-text">
  <%= link_to "Set up New House", onboarding_houses_path %>
  </div>
  <div>
    <p>></p>
  </div>
</div>

<div class="d-flex justify-content-between mx-5">
  <div class="round-small-house">
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="23" height="23"><path fill="none" d="M0 0h24v24H0z"/><path d="M9 19h3v-6.058L8 9.454l-4 3.488V19h3v-4h2v4zm12 2H3a1 1 0 0 1-1-1v-7.513a1 1 0 0 1 .343-.754L6 8.544V4a1 1 0 0 1 1-1h14a1 1 0 0 1 1 1v16a1 1 0 0 1-1 1zm-5-10v2h2v-2h-2zm0 4v2h2v-2h-2zm0-8v2h2V7h-2zm-4 0v2h2V7h-2z"/></svg>
  </div>
 <div class="round-small-text">
    <%= link_to "Switch House", houses_path %>
  </div>
  <div>
    <p>></p>
  </div>
</div>

<div class="d-flex justify-content-between mx-5">
  <div class="round-small-house">
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="23" height="23"><path fill="none" d="M0 0h24v24H0z"/><path d="M14 14.252V22H4a8 8 0 0 1 10-7.748zM12 13c-3.315 0-6-2.685-6-6s2.685-6 6-6 6 2.685 6 6-2.685 6-6 6zm6 4v-3.5l5 4.5-5 4.5V19h-3v-2h3z"/></svg>
  </div>
  <div class="round-small-text">
      <%= link_to "Leave House", house_memberships_path(@house) %>
  </div>
  <div>
    <p>></p>
  </div>
</div>

<div class="ml-5">
  <h6>Settings</h6>
</div>


<div class="d-flex justify-content-between mx-5">
  <div class="round-small-settings">
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="23" height="23"><path fill="none" d="M0 0h24v24H0z"/><path d="M6.265 3.807l1.147 1.639a8 8 0 1 0 9.176 0l1.147-1.639A9.988 9.988 0 0 1 22 12c0 5.523-4.477 10-10 10S2 17.523 2 12a9.988 9.988 0 0 1 4.265-8.193zM11 12V2h2v10h-2z"/></svg>
  </div>
  <div class="round-small-text">
    <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
  </div>
  <div>
    <p>></p>
  </div>
</div>

<div class="mb-5 pb-5"></div>

app/views/houses/show.html.erb
<%= link_to "Log out", destroy_user_session_path, method: :delete %>
<h1>Show page</h1>

<h2><%= @house.name %></h2>

<ul>
  <li> Name: <%= @house.name %> </li>
  <li> Email: <%= @house.email %> </li>
  <li> House balance: <%= @house.house_balance %>€</li>
</ul>

<h4>House Members</h4>

<ul>
  <% @house.users.each do |user| %>
  <li><%= user.name %></li>
  <% end %>
</ul>

<ul>
  <li><%= link_to "Edit a House", edit_house_path(@house)%></li>
  <li><%= link_to "Delete a House", house_path(@house), method: :delete %></li>
  <li><%= link_to "Go back", houses_path %></li>
</ul>

<!-- Try to generate the link using the rails routes prefix
"http://localhost:3000/users/sign_up?house_id=#{house.id}"
"new_user_registration" + "?house_id=#{house.id}" -->

<p>To invite new housemates send this link: http://localhost:3000/users/sign_up?house_id=<%= @house.id %></p>
<!--   <i class="fas fa-trash-alt"></i> <i class="fas fa-edit"></i> -->