config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  mount StripeEvent::Engine, at: '/stripe-webhooks'

  root to: 'pages#home'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :after_signup

  resources :houses do
    collection do
      get :onboarding
    end

    member do
      get :onboarding_link
      get :settings
    end

    resources( :bills, {only: [:edit, :update, :new, :create]})
    # Method (symbol, hash { key/symbol value/array})
    resources :memberships, only: [:index, :destroy]
    resources :shares, only: [:index] do
      collection do
        get :history
      end
    end

    resources :payments, only: [:show, :create]

    get 'pre_payment/:id', to: 'payments#pre_payment', as: 'pre_payment'
  end

  resources( :bills, {only: [:destroy]})

  resources :shares, only: [:edit, :update]



end

app/views/pages/home.html.erb
<main>
 <!-- <div id="shapes">
    <%= image_tag "yellow-circle.svg", alt: "circle", class: 'shape' %>
    <br>
    <%= image_tag "sand-triangle.svg", alt: "triangle", class: 'shape' %>
    <br>
    <%= image_tag "blue-square.svg", alt: "square", class: 'shape' %>
    <h1>Even</h1>
  </div>
-->
  <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active home-main">
      <div id="shapes">
        <%= image_tag "yellow-circle.svg", alt: "circle", class: 'shape' %>
        <br>
        <%= image_tag "sand-triangle.svg", alt: "triangle", class: 'shape' %>
        <br>
        <%= image_tag "blue-square.svg", alt: "square", class: 'shape' %>
        <h1>Even</h1>
      </div>
    </div>
    <div class="carousel-item">
      <%= image_tag "capital-logo.svg", alt: "logo", class: 'logo-carousel' %>
      <div class="mt-5 pt-5"></div>
      <div class="carousel-div">
        <h4 class="mx-5 text-center">To everyone who’s ever been in charge of finance in a house share: <br><br> Bills, am I right? <br><br> 😱💸</h4>
      </div>
    </div>
    <div class="carousel-item">
      <%= image_tag "capital-logo.svg", alt: "logo", class: 'logo-carousel' %>
      <div class="mt-5 pt-5"></div>
        <div class="carousel-div">
          <h4 class="mx-5 text-center">Even is here for housemates who just want to be good mates. <br><br> No money talk. No chief bill-payer. <br><br>❤️</h4>
        </div>
    </div>
    <div class="carousel-item">
      <%= image_tag "capital-logo.svg", alt: "logo", class: 'logo-carousel' %>
      <div class="mt-5 pt-5"></div>
        <div class="carousel-div">
          <h4 class="mx-5 text-center">Expenses come out of a joint account. <br><br> Payments are easy and tracked. <br><br> The race for the quickest payer begins! <br><br>🎉 🏁</h4>
        </div>
    </div>
  </div>
</div>

  <div class="start-button-container home-main">
    <%= link_to new_user_registration_path, class: 'btn btn-danger' do %>
      <span>get started &nbsp;&nbsp;&nbsp;&nbsp; →</span>
    <% end %>
  </div>
</main>

app/views/pages/settings.html.erb
<div class="mx-5 mt-5">
  <button class="round-button-name">
  <h1>
      <%= current_user.initials %>
  </h1>
  </button>
</div>

<div class="mt-3 mb-5">
  <h3 class="text-center mr-1">Hey, <%= current_user.first_name %>
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="14" height="14"><path fill="none" d="M0 0h24v24H0z"/><path d="M7.291 20.824L2 22l1.176-5.291A9.956 9.956 0 0 1 2 12C2 6.477 6.477 2 12 2s10 4.477 10 10-4.477 10-10 10a9.956 9.956 0 0 1-4.709-1.176zM7 12a5 5 0 0 0 10 0h-2a3 3 0 0 1-6 0H7z"/>
  </svg>
  </h3>
</div>


<div class="ml-5">
  <h6>You</h6>
</div>

<div class="d-flex justify-content-between mx-5">
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24"><path fill="none" d="M0 0h24v24H0z"/><path d="M9.243 19H21v2H3v-4.243l9.9-9.9 4.242 4.244L9.242 19zm5.07-13.556l2.122-2.122a1 1 0 0 1 1.414 0l2.829 2.829a1 1 0 0 1 0 1.414l-2.122 2.121-4.242-4.242z"/>
  </svg>
  <%= link_to "Update Details", edit_user_registration_path %>
  <p>></p>
</div>

<div class="ml-5">
  <h6>Houses</h6>
</div>

<div class="d-flex justify-content-between mx-5">
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24"><path fill="none" d="M0 0h24v24H0z"/><path d="M20 20a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1v-9H1l10.327-9.388a1 1 0 0 1 1.346 0L23 11h-3v9zM7.5 13a4.5 4.5 0 1 0 9 0h-2a2.5 2.5 0 1 1-5 0h-2z"/></svg>
  <%= link_to "House Details", houses_path %>
  <p>></p>
</div>

<div class="d-flex justify-content-between mx-5">
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24"><path fill="none" d="M0 0h24v24H0z"/><path d="M14 14.252V22H4a8 8 0 0 1 10-7.748zM12 13c-3.315 0-6-2.685-6-6s2.685-6 6-6 6 2.685 6 6-2.685 6-6 6zm6 4v-3h2v3h3v2h-3v3h-2v-3h-3v-2h3z"/></svg>
  <%= link_to "Invite New Members"%>
  <p>></p>
</div>

<div class="d-flex justify-content-between mx-5">
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24"><path fill="none" d="M0 0h24v24H0z"/><path d="M10.313 11.566l7.94-7.94 2.121 2.121-1.414 1.414 2.121 2.121-3.535 3.536-2.121-2.121-2.99 2.99a5.002 5.002 0 0 1-7.97 5.849 5 5 0 0 1 5.848-7.97zm-.899 5.848a2 2 0 1 0-2.828-2.828 2 2 0 0 0 2.828 2.828z"/></svg>
  <%= link_to "Set up New House", new_house_path %>
  <p>></p>
</div>

<div class="d-flex justify-content-between mx-5">
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24"><path fill="none" d="M0 0h24v24H0z"/><path d="M9 19h3v-6.058L8 9.454l-4 3.488V19h3v-4h2v4zm12 2H3a1 1 0 0 1-1-1v-7.513a1 1 0 0 1 .343-.754L6 8.544V4a1 1 0 0 1 1-1h14a1 1 0 0 1 1 1v16a1 1 0 0 1-1 1zm-5-10v2h2v-2h-2zm0 4v2h2v-2h-2zm0-8v2h2V7h-2zm-4 0v2h2V7h-2z"/></svg>
  <%= link_to "Switch House", houses_path %>
  <p>></p>
</div>

<div class="d-flex justify-content-between mx-5">
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24"><path fill="none" d="M0 0h24v24H0z"/><path d="M14 14.252V22H4a8 8 0 0 1 10-7.748zM12 13c-3.315 0-6-2.685-6-6s2.685-6 6-6 6 2.685 6 6-2.685 6-6 6zm6 4v-3.5l5 4.5-5 4.5V19h-3v-2h3z"/></svg>
  <%= link_to "Leave House", houses_path %>
  <p>></p>
</div>

<div class="ml-5">
  <h6>Settings</h6>
</div>


<div class="d-flex justify-content-between mx-5">
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24"><path fill="none" d="M0 0h24v24H0z"/><path d="M6.265 3.807l1.147 1.639a8 8 0 1 0 9.176 0l1.147-1.639A9.988 9.988 0 0 1 22 12c0 5.523-4.477 10-10 10S2 17.523 2 12a9.988 9.988 0 0 1 4.265-8.193zM11 12V2h2v10h-2z"/></svg>
  <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
  <p>></p>
</div>

<%= link_to "Go back" %>